python3 -m hred.train \
    --train_path=/home/shuuki4/sandbox_project/HRED/data/4lines/train_corpus.txt \
    --val_path=/home/shuuki4/sandbox_project/HRED/data/4lines/val_corpus.txt \
    --vocab_path=/home/shuuki4/sandbox_project/HRED/data/4lines/vocab.txt \
    --save_dir=/home/shuuki4/sandbox_project/HRED/results/4lines/$1 \
    --word_embedding_dim=256 \
    --num_rnn_layers=4 \
    --num_bidi_layers=1 \
    --num_rnn_units=512 \
    --optimizer=adam \
    --initial_learning_rate=1e-3 \
    --start_decay_step=10000 \
    --lr_decay_steps=5000 \
    --lr_decay_rate=0.96 \
    --batch_size=64